- hosts: localhost
  become: yes
  gather_facts: no

  tasks:

    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh

    - name: Remove old WAR deployment
      file:
        path: /opt/tomcat/webapps/Ansible.war
        state: absent

    - name: Remove old expanded app
      file:
        path: /opt/tomcat/webapps/Ansible
        state: absent

    - name: Copy WAR file
      copy:
        src: /var/snap/jenkins/5022/workspace/ansible/target/maven-webapp.war
        dest: /opt/tomcat/webapps/Ansible.war
        remote_src: yes

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
